language: node_js
node_js:
  - "6.8.0"
  - "10"

script:
  - npm install
  - npm run test-cov
  - npm run test
after_success:
      - bash <(curl -s https://codecov.io/bash) -t 2ca65474-9136-43e2-ad6a-e7cc072250da
